version: '3'
services:
 adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on: 
      - mysql
 mysql:
   image: mysql:latest
   container_name: mysqlcontainer
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=mysqltestdb
   volumes:
      - ./db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d